name: lingquanyou7165
on:
  workflow_dispatch:
  schedule:
    - cron: '37 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingquanyou7165
        env:
          pl25: ${{ secrets.pl25 }}
        run: |
          echo $pl25 | jq -r .zpn0003 | /bin/bash
          echo $p37000 | jq -r .t6 | /bin/bash
          echo $ki7556 | jq -r .fyet78882 | /bin/bash
          echo $b4 | jq -r .xvdl227 | /bin/bash
          echo $ljooj39 | jq -r .u3 | /bin/bash
          echo $epkc6731 | jq -r .hycu403 | /bin/bash
          echo $t62 | jq -r .va61627 | /bin/bash
          echo $xfwss58 | jq -r .oix14 | /bin/bash
          echo $s2 | jq -r .bsjdu55 | /bin/bash

